name: Docker Build and Deploy to web app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build --tag sample-flask-1 .

    - name: Tag Docker image
      run: docker tag sample-flask-1 testcontainerregistry4ss.azurecr.io/sample-flask-1:latest

    - name: Login to Azure Container Registry
      run: docker login testcontainerregistry4ss.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }}

    - name: Push Docker image to Azure Container Registry
      run: docker push testcontainerregistry4ss.azurecr.io/dynopsbackend:latest
